version: '3.8'
services:
  go-api:
    build:
      context: .
      dockerfile: services/go-api/Dockerfile
    ports:
      - "9464:9464"
      - "8080:8080"
    environment:
      OTEL_SERVICE_NAME: go-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_PROMETHEUS_PORT: 9464 # Prometheus metrics port
